bump versions and fix some clippy warnings
freenet/freenet-core pull request #1083
Opened 2024-05-14 13:31 UTC by al8n

2024-05-14 14:09 UTC, iduartgomez requested changes
Merge pending changes in stdlib and point to main head in this pr and we can merge

2024-05-14 15:23 UTC, al8n commented on stdlib
The commit in this PR is the latest commit of stdlib, so do we want to also bump versions in stdlib?

2024-05-14 16:03 UTC, iduartgomez commented on stdlib
yes please

2024-05-15 12:26 UTC, iduartgomez approved these changes
Accepted stdlib or, merge that and then you this

2024-05-15 13:37 UTC, merged