Enable compilation on windows.
freenet/freenet-core pull request #965
Opened 2024-01-19 20:32 UTC by gogo2464

rebase of https://github.com/freenet/freenet-core/pull/956

2024-01-20 08:40 UTC, iduartgomez requested changes
There are some errors

2024-01-20 08:40 UTC, iduartgomez commented on crates/fdev/src/build.rs
> +                    let webpack = web_config
this is redundant if we are checking for webpack already above (line 277);
the else condition of 298 won't event be ever be executed here, so it needs to be moved to an else branch for line 277

2024-01-22 20:50 UTC, gogo2464 commented
@iduartgomez I now have this issue from another part of code:

```

error[E0614]: type `freenet_stdlib::prelude::ContractInstanceId` cannot be dereferenced
   --> crates\core\src\contract\executor\runtime.rs:867:22
    |
867 |                 key: *original_key.id(),
    |                      ^^^^^^^^^^^^^^^^^^
```


is it related to my own codebase or is it due to the original freenet codebase?

2024-01-22 21:17 UTC, gogo2464 commented
see https://github.com/freenet/freenet-core/actions/runs/7617268691/job/20745918244?pr=965#step:7:928

2024-01-22 21:26 UTC, iduartgomez commented
> @iduartgomez I now have this issue from another part of code:
> 
> ```
> 
> error[E0614]: type `freenet_stdlib::prelude::ContractInstanceId` cannot be dereferenced
>    --> crates\core\src\contract\executor\runtime.rs:867:22
>     |
> 867 |                 key: *original_key.id(),
>     |                      ^^^^^^^^^^^^^^^^^^
> ```
> 
> is it related to my own codebase or is it due to the original freenet codebase?

Is because the stdlib commit change. That doesn't have to change.

2024-01-22 22:10 UTC, gogo2464 commented
cool

2024-01-22 22:11 UTC, gogo2464 commented
how to fix the cicd then?

2024-01-25 22:07 UTC, netsirius commented
@gogo2464 I have solved the out-of-sync issue with the stdlib commit. The next step is to resolve the Clippy errors.

2024-01-27 09:02 UTC, iduartgomez approved these changes

2024-01-27 09:02 UTC, merged